print("Hello Igor!")
require("config.settings")
require("config.open-last-file")
require("config.hunt-messages")
require("config.lazy")
require("config.colorscheme")
require("config.vim-keymaps")
require("config.lsp-keymaps")
require("config.lsp")
